[package]
name = "yew-ui-components"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew", features=["csr"] }
yew-hooks = { git = "https://github.com/jetli/yew-hooks" }
log = "0.4.6"
wasm-logger = "0.2.0"