[package]
name = "component-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew" }
yew-ui-components = { path = ".." }
log = "0.4.6"
wasm-logger = "0.2.0"